name: asgard_gv_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - aria2=1.37.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.2
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.7
  - aws-c-io=0.18.1
  - aws-c-mqtt=0.12.3
  - aws-c-s3=0.7.15
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - awscli=2.27.5
  - awscrt=0.26.1
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - biopython=1.85
  - blast=2.16.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cryptography=43.0.1
  - curl=8.13.0
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - diamond=2.1.11
  - distro=1.8.0
  - docutils=0.19
  - entrez-direct=22.4
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - foldseek=10.941cd33
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - gawk=5.3.1
  - gmp=6.3.0
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.17.2
  - iqtree=2.4.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libcxx=20.1.4
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.23.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.3
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mmseqs2=17.b804f
  - mpfr=4.2.1
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nbstripout=0.8.1
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy=2.0.2
  - openjpeg=2.5.3
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.69
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.9.22
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.24.0
  - rpsbproc=0.5.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.8
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.1.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tmalign=20220227
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - trimal=1.5.0
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=1.26.19
  - veryfasttree=4.0.5
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wget=1.21.4
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - arcadia-pycolor==0.6.1
      - async-timeout==5.0.1
      - colorspacious==1.1.2
      - counter==1.0.0
      - cython==3.0.12
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - fair-esm==2.0.0
      - filelock==3.18.0
      - freesasa==2.2.1
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - ftpretty==0.4.0
      - getsequence==2.2.1
      - git-filter-repo==2.47.0
      - goatools==1.4.12
      - joblib==1.4.2
      - kaleido==0.2.1
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - metapredict==3.0.1
      - mpmath==1.3.0
      - multidict==6.4.3
      - narwhals==1.37.1
      - networkx==3.2.1
      - openpyxl==3.1.5
      - pandas==1.5.3
      - plotly==6.0.1
      - propcache==0.3.1
      - protfasta==0.1.15.2
      - pydot==4.0.0
      - pytorch-lightning==2.5.1.post0
      - rich==14.0.0
      - scikit-learn==1.6.1
      - sqlitedict==1.7.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - torch==2.7.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - xlsxwriter==3.2.3
      - yarl==1.20.0
